### ISSUE TITLE
Display off on HP Reverb G2 

### ISSUE THREAD

**Issue by hi7** [OpenHMD/OpenHMD#323]
I have build from master and when I run the simple example I got:
[EE] Failed to issue command 08: 17 00 01
[EE] Could not read config from the firmware
resolution:              0 x 0

**Comment by l33tlinuxh4x0r** [comment]
I am thinking about getting this headset... Is it supported at all yet? Does it work at all with OpneHMD/Linux?

**Comment by letoram** [comment]
Not supported yet, the magic sequence for turning the display on has changed from the G1 to the G2.

**Comment by l33tlinuxh4x0r** [comment]
How difficult would it be to find the new magic sequence and add it to OpenHMD?

**Comment by thaytan** [comment]
https://github.com/thaytan/OpenHMD/tree/dev-reverb-g2 lights up the reverb G2 for me if anyone wants to try that. There's lots more to do besides of course - eye rotations is wrong and there's very noticeable gyro drift on mine.

I didn't find a fix for the ` [EE] Failed to issue command 08: 17 00 01` error. It happens reliably on the first attempt after plugging in, but it works on the 2nd attempt.

**Comment by hi7** [comment]
With https://github.com/thaytan/OpenHMD/tree/dev-reverb-g2 I got rid of the error message 
"[EE] Failed to issue command 08: 17 00 01" 
at second attempt to plug in, but I still got no light. Do I miss something.

**Comment by thaytan** [comment]
Others on IRC have also said this doesn't work for them... but it does for me, so there's something else going on.

**Comment by l33tlinuxh4x0r** [comment]
I haven't tried it yet but maybe the initialization code might be generated basted on HWID or serial number in addition so that it would work for you but not everyone else? Just a theory. I'll boot to Linux and try in a bit.

**Comment by thaytan** [comment]
There is nothing uniquely extracted from my headset in that sequence - I just fiddled with the timing of the G1 sequence and added some retries to the config retrieval

**Comment by l33tlinuxh4x0r** [comment]
OK so I tested it... My display doesn't light up also I needed to run as root to get it working. The simple test program then seemed to work. I will try running a second time to see if it wakes up. 2nd time it still doesn't light up but it is "working".

**Comment by thaytan** [comment]
If you need to run as root, then you are missing a udev rule. https://gitlab.freedesktop.org/monado/utilities/xr-hardware has a rule for the G2 already.

**Comment by l33tlinuxh4x0r** [comment]
> If you need to run as root, then you are missing a udev rule. https://gitlab.freedesktop.org/monado/utilities/xr-hardware has a rule for the G2 already.

Thanks.

**Comment by l33tlinuxh4x0r** [comment]
I get the tracking now but no screen on.

**Comment by thaytan** [comment]
I guess when we understand why it's working for me it'll be obvious in hindsight.

**Comment by l33tlinuxh4x0r** [comment]
> 
> 
> I guess when we understand why it's working for me it'll be obvious in hindsight.

What OS are you using?

**Comment by l33tlinuxh4x0r** [comment]
> 
> 
> I'm testing on a Fedora system

Have you tried using a Live system or a fresh install on another disk to see if you can replicate your results?

**Comment by l33tlinuxh4x0r** [comment]
OK... I got the screen to come on!!! I'm using Archlinux with X11, gnome and the latest branch from thaytan.

This time I did ```git clone --branch dev-reverb-g2 https://github.com/thaytan/OpenHMD.git
```
instead of just git clone. Also it didn't seem to work the first time. Now it is lit up... It doesn't want to turn off though.

**Comment by thaytan** [comment]
Ah. If you didn't switch branches before, it would not have been running the Reverb init code, and just treating it as an unknown WMR headset.

**Comment by l33tlinuxh4x0r** [comment]
> 
> 
> Ah. If you didn't switch branches before, it would not have been running the Reverb init code, and just treating it as an unknown WMR headset.

Yeah that was the issue... I'm curious if that is why other people were having issues as well.

**Comment by l33tlinuxh4x0r** [comment]
I am getting my headset to turn on 100% of the time. I even tried to play steamvr using SteamVR-OpenHMD however I couldn't get that to work.. It did wake up the headset but it wouldn't let me display anything... It just displays as another desktop. I can't use it for VR.

**Comment by thaytan** [comment]
This is just init code - the driver still needs to report the right screen resolution and viewport mappings before SteamVR will be able to find it, and distortion info if we want it to look any good

**Comment by hi7** [comment]
I'm on Fedora too and sometimes the G2 got detected with some flicker on my main monitor but no light on the G2 with dev-reverb-g2 branch.

**Comment by thaytan** [comment]
> I'm on Fedora too and sometimes the G2 got detected with some flicker on my main monitor but no light on the G2 with dev-reverb-g2 branch.

Are you able to test on Windows on the same hardware / ports?

**Comment by hi7** [comment]
SteamVR/WMR works with the G2 on Win10, if you mean that.

**Comment by thaytan** [comment]
Thanks yes - there's enough people have trouble with G2 even under Windows that I want to make sure it's expected to work when testing here :)

**Comment by l33tlinuxh4x0r** [comment]
> 
> 
> This is just init code - the driver still needs to report the right screen resolution and viewport mappings before SteamVR will be able to find it, and distortion info if we want it to look any good

Is anyone working on this? If not could you please point me in the right direction so I can try to tinker with it.

**Comment by thaytan** [comment]
I probably won't be pushing it further in the next few weeks.  https://github.com/thaytan/OpenHMD/blob/670a2e666d217a4f218239c3e96f8f3e709ab868/src/drv_wmr/wmr.c#L533 is the right area if you want to play. I think it should be getting the right resolution details from the config blob already actually - so I'm not sure why Steam didn't find it.

**Comment by l33tlinuxh4x0r** [comment]
Just rebuilt everything as root and installed the latest OpenHMD thaytan version and it is working in steamVR! only problem is that the video is rotated 90 degreees to the right. So I need to flip the image 90 degrees left to be able to test more. P.S. I had to enable direct display mode otherwise it just overlays stuff on my desktop. With direct display mode it appears to be working!

**Comment by l33tlinuxh4x0r** [comment]
Looks like the controllers aren't working either and no VR programs will run but the headset is active and at the "mountain" screen 90 degrees flipped.

**Comment by l33tlinuxh4x0r** [comment]
I got no man's sky to run, no controllers and everything is 90 degrees rotated... hope that this helps. Also not as clear as in windows so maybe the lens distortion is wrong.
![Screenshot from 2021-03-28 13-51-51](https://user-images.githubusercontent.com/1632838/112762299-f1eeee00-8fcc-11eb-9e23-6c5a9c4c2b0b.png)

**Comment by l33tlinuxh4x0r** [comment]
For anyone that wants to test/help, I'm posting how I got it _working_.

```
mkdir VRStuff
cd VRStuff
git clone --recursive https://github.com/ChristophHaag/SteamVR-OpenHMD.git
cd SteamVR-OpenHMD/subprojects
rm openhmd -R
git clone --branch dev-reverb-g2 https://github.com/thaytan/OpenHMD.git openhmd
cd ..
mkdir build
cd build
cmake ..
make
cd ../..
git clone --branch dev-reverb-g2 https://github.com/thaytan/OpenHMD.git
cd OpenHMD
mkdir build
cd build
cmake ..
make
sudo make install
cd ../..
cd SteamVR-OpenHMD
./register.sh
```
That should get you up and running... Don't forget to enable direct display mode once you get SteamVR working so that it displays on your headset.

**Comment by fluffrabbit** [comment]
You can install OpenHMD globally, but AFAIK you don't have to. SteamVR uses the copy in the SteamVR-OpenHMD folder. Correct me if I'm wrong.

**Comment by l33tlinuxh4x0r** [comment]
> You can install OpenHMD globally, but AFAIK you don't have to. SteamVR uses the copy in the SteamVR-OpenHMD folder. Correct me if I'm wrong.

I will test this... It didn't seem to work before but I will test again and report back.

**Comment by l33tlinuxh4x0r** [comment]
> You can install OpenHMD globally, but AFAIK you don't have to. SteamVR uses the copy in the SteamVR-OpenHMD folder. Correct me if I'm wrong.

You are correct... No need for a global install. Will do a reboot to be 100% sure in a bit.

Updated instructions:

```
mkdir VRStuff
cd VRStuff
git clone --recursive https://github.com/ChristophHaag/SteamVR-OpenHMD.git
cd SteamVR-OpenHMD/subprojects
rm openhmd -R
git clone --branch dev-reverb-g2 https://github.com/thaytan/OpenHMD.git openhmd
cd ..
mkdir build
cd build
cmake ..
make
cd..
./register.sh
```

**Comment by l33tlinuxh4x0r** [comment]
I ran steam from terminal and got a bunch of ```[EE] unknown message type: ``` errors. The number changed every time I either moved the HMD error 23 iirc and a bunch of different error numbers when I moved the controllers.

**Comment by fluffrabbit** [comment]
The `[EE]` errors are printed by OpenHMD AFAIK. I have not done this myself, but if things are generally working then I would blame it on deficiencies in OpenHMD's driver for your device.

**Comment by l33tlinuxh4x0r** [comment]
I have made some changes to thaytan's code... First Headsets should always work now even on cold boot! No more having to run OpenHMD 2 or 3 times to get your headset to work. I also separated reverb and reverb g2 info and error messages to be more clear. The above problems are still a thing though... 90 degree rotation, controllers don't work etc.

I have updated instructions for anyone that wants to test. Also I put it in master not dev branch so it is easier to checkout.

```
mkdir VRStuff
cd VRStuff
git clone --recursive https://github.com/ChristophHaag/SteamVR-OpenHMD.git
cd SteamVR-OpenHMD/subprojects
rm openhmd -R
git clone https://github.com/l33tlinuxh4x0r/OpenHMD.git openhmd
cd ..
mkdir build
cd build
cmake ..
make
cd ..
./register.sh
```

Here is my repo for review https://github.com/l33tlinuxh4x0r/OpenHMD.git

**Comment by thaytan** [comment]
That's a bit ugly. By rebasing on my repo's git master instead of upstream you've pulled in extra commits that can never got upstream (me updating the README to provide Rift status updates for example), and by squashing all the existing G2 commits into one you've thrown away attribution and made it hard to see what you've changed.

Finally, a potentially infinite loop reading the config isn't upstreamable. It has to give up at some point.

**Comment by l33tlinuxh4x0r** [comment]
> That's a bit ugly. By rebasing on my repo's git master instead of upstream you've pulled in extra commits that can never got upstream (me updating the README to provide Rift status updates for example), and by squashing all the existing G2 commits into one you've thrown away attribution and made it hard to see what you've changed.
> 
> Finally, a potentially infinite loop reading the config isn't upstreamable. It has to give up at some point.

Thanks for the heads up... I will try to fix the git repos... I'm not very good at git unfortunately.

I figured that the infinite loop was a bad thing. Maybe I could make it loop like 10 times or something?

**Comment by l33tlinuxh4x0r** [comment]
I also made a hard limit of 10 tries for getting the config from the headset. That should be enough. My headset seems to need 3 checks, not sure about others. I might play around with it more to see if there is a more elegant way of getting the config. Maybe just pinging the headset a couple of times before trying? Not sure how to code that though.

**Comment by thaytan** [comment]
I'd like to restructure all that code to:
 * Add an enum for known WMR headset types
 * Add a const array that maps VID/PID and description strings for the aux device to WMR headset type, init/deinit funcs and a headset name string for debug / pretty printing.

Also, your idea to keep things on master in your repo isn't bad. Jump back on IRC if you need git help.

**Comment by thaytan** [comment]
If we could it would be better to figure out what the ` [EE] Failed to issue command 08: 17 00 01` return code actually means while reading firmware and handle it - that would avoid needing to retry at all.

**Comment by thaytan** [comment]
I've merged https://github.com/thaytan/OpenHMD/pull/35 from @ph5 into my dev-reverb-g2 branch, which fixes config reads properly here.

**Comment by l33tlinuxh4x0r** [comment]
> I've merged [thaytan#35](https://github.com/thaytan/OpenHMD/pull/35) from @pH5 into my dev-reverb-g2 branch, which fixes config reads properly here.

I can confirm that this works.

**Comment by l33tlinuxh4x0r** [comment]
@thaytan In my experience with the new error 23 fix the following lines of code aren't needed anymore. For me it gets the config on the first try every time now.

```
	// Try twice to read the config. It fails the first time on HP G2
	// after a fresh plug-in
	if (config == NULL)
		config = read_config(priv);
```

**Comment by l33tlinuxh4x0r** [comment]
Should we mark this bug as fixed since the device turns on now and open another bug for the rotation/sensors/controllers not working?

**Comment by TheOnlyJoey** [comment]
> Should we mark this bug as fixed since the device turns on now and open another bug for the rotation/sensors/controllers not working?

Once a PR has been merged we can close this topic, which is not the case at this moment.

**Comment by l33tlinuxh4x0r** [comment]
Is anyone doing a pull request? What is holding this up, just lack of time?

**Comment by TheOnlyJoey** [comment]
> Is anyone doing a pull request? What is holding this up, just lack of time?

Please don't spam the issue, things happen when they happen.

**Comment by LoganDark** [comment]
l'm interested in using OpenHMD as a replacement for WMR on machines without appx support (so can't run the Windows Mixed Reality Portal app). l own a HP Reverb G2 as well. ls there anything l can do to help the process of adding support for this headset?

**Comment by l33tlinuxh4x0r** [comment]
After playing with the driver for hours... I figured something out. I can get the headset to stay the correct orientation if I comment out the following line in the source code. line 181 `*(quatf*)out = priv->sensor_fusion.orient;` The problem with that is there is no tracking at all if I do this (which is to be expected) however it tells me that this headset is doing something funny with ROTATION_QUAT I'll look into this more and hopefully I'll get lucky and find a fix.

**Comment by thaytan** [comment]
The problem is that this headset has the IMU rotated differently to the other WMR headsets that the driver was written for. The correct solution is to read the IMU orientation from the firmware block. In the meantime, you can change the order of array accesses in `vec3f_from_hololens_gyro()` and `vec3f_from_hololens_accel()`. Instead of 1/0/2 for X/Y/Z axis ordering, just change the indices to 0/1/2 for X/Y/Z.

**Comment by l33tlinuxh4x0r** [comment]
I have narrowed this down to the accel causing the rotation(I think). I don't understand what you are saying should be changed to get this to work though.

**Comment by thaytan** [comment]
I have pushed a commit to https://github.com/thaytan/OpenHMD/tree/dev-reverb-g2 that implements what I mean.

**Comment by l33tlinuxh4x0r** [comment]
I tested and added a patch that fixes a bug in the looking up and down functions of the headset. I submitted a pull request. https://github.com/thaytan/OpenHMD/pull/39

**Comment by muskwasis** [comment]
How could we add more resolutions and refresh rates? I get 2280x1440@90hz, but the device also supports 4320x2160@90hz and 4320x2160@60hz.

**Comment by isopix** [comment]
I never played with this device.

***@***.*** is native, the problem could be Graphics Card or
DisplayPort cable.
Try upgrading firmware or drivers.


xrandr should repport supported resolutions.

**Comment by spiderbit** [comment]
@thaytan did you only add this rotation patch for the G2 or also the G1 because I have here a G1 and its 90 rotated to the right.

Btw because controllers don't work, I think it's possible to get the steamvr to not expect a controller or are they only used for pressing buttons or something?

**Comment by spiderbit** [comment]
Somehow all broke after tracking and displaying worked, I tried 100 things reinstalling uninstalling different parts look over the Steamvr-openhmd doku but something went wrong maybe somebody can look over my vrserver.txt and the output of vrstartup and tell me what I did wrong. Did thaytan g2 branch as subproject and usde the same commands but I get some "error occured 203 in steamvr"
[vrserver.txt](https://github.com/OpenHMD/OpenHMD/files/7230687/vrserver.txt)
[run.log](https://github.com/OpenHMD/OpenHMD/files/7230688/run.log)

**Comment by spiderbit** [comment]
Well tried reinstall steam like 10 times the first time it worked after fresh installation for 1 time or so to set it up but then it did not work again.
Even modified the PKGBUILD for openhmd-steamvr package, but of course didn't help, but maybe can do something with it.
[PKGBUILD.txt](https://github.com/OpenHMD/OpenHMD/files/7232564/PKGBUILD.txt)

**Comment by thaytan** [comment]
203 error is apperently VRInitError_Driver_NotLoaded, but I don't have any guesses as to exactly what is wrong, sorry.

**Comment by spiderbit** [comment]
@thaytan thanks for looking at the log, I am a bit lost in what to attempt next did reinstall steam (the user installation part) 10 times or so, 1 time it worked to initiate but then stopped working the other times it didn't change anything.

Any idea what I could do, install another version of linux would be the only thing I could think of, a bit stuck... steam sucks... wish VR would not depend on steam so much.

**Comment by thaytan** [comment]
Do the OpenHMD simple and opengl examples work reliably and start up every time? I'd check that - the problem may be that the initialisation is not reliable on your system.

**Comment by spiderbit** [comment]
No it does not work reliable each time, but I use your branch, before that it did not work at all...

**Comment by spiderbit** [comment]
I use that branch:
https://github.com/thaytan/OpenHMD/tree/dev-reverb-g2

I have a G1 but I also tried the branch from kflansburg with similar results...

**Comment by thaytan** [comment]
No, it's not expected for the config reading to fail now (it used to be due to a packet we didn't handle, but that got fixed).

You could try reverting 71a0a3ee21b1c90e72393204821b81c142da5023 in OpenHMD and see if that helps

**Comment by spiderbit** [comment]
Well I get further the openhmd simple works, the orientation is now wrong but it "detects" the device and let me set it up.

Steamvr first starts to display the picture in full screen on the monitor and not the device the window that says I should remove the HMD which should be displayed on the HMD and not the monitor. Then it says a lot that it could not start in direct mode after retrying that 5 times it takes a bit longer and says "something is wrong a key component of steamvr isn't working correctly. Please reinstall SteamVR.

**Comment by spiderbit** [comment]
@thaytan after testing a lot around with different commit versions of your branch and then reseting back to the latest of dev-reverb-g2 branch it worked again for exactly 1 time.

First thought it might been because I updated steam to beta, but it only worked once. I tried to catch some messages and differences.

In short as far as I can tell I always get a unknown message type 2 Error when it don't works:
[steam vr errors.txt](https://github.com/OpenHMD/OpenHMD/files/7256118/steam.vr.errors.txt)

It's funny because openhmd-simple-example always detects the device but it seems to not work in steam / openvr wrapper.

What's also strange is that sometimes the login manager gdm seems to detect the HMD as monitor and then I have to blindly enter my passwort, but most of the time not.

Another small part is that I can setup in gnome the HMD as dual device when I set the refresh rate to 60hz but it doesn't let me change to 90hz and even in 60hz xrandr don't shows that setting even I see the gnome desktop in the HMD:

```
DP-2 connected (normal left inverted right x axis y axis)
   4320x2160     90.00 +  60.00
```

**Comment by spiderbit** [comment]
Ok I might be onto something, planted the ssd with the fedora I used for testing into my other pc with a I think hd 5950 and used a small vr cable that came with the device for some reason that has a mini-dp connector instead of the normal sized dp, so I could connect it to that graphiccard that has only such connectors, while it did not fully work, the tracking works in simple and with steamvr it opens don't crashes don't have coredumps, even if I open it up repetitively.

So I will order now a displayport-minidp adapter so I can use the normal cable with this graphic card and then test this with my arch linux install that worked sometimes and report back what I will see. But something changed, same software and I got coredumps before now I don't.

If that would work now then it would not be a general bug in radeonsi or the hd5950 uses a different X driver?

**Comment by spiderbit** [comment]
Hey @thaytan
I now have bought a mini-dp to dp adapter so that I can use my HMD on my older gpu (HD 7950) I still get a error in steamvr but it's different now: 

gdb shows me like 20 threads most like that:

```
Thread 20 (Thread 0x7fa1c0c53640 (LWP 6373)):
#0  0x00007fa1d21b28ca in __futex_abstimed_wait_common64 () from /usr/lib/libpthread.so.0
#1  0x00007fa1d21ac270 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#2  0x00007fa1cc4538cc in ?? () from /usr/lib/dri/radeonsi_dri.so
#3  0x00007fa1cc44cfa8 in ?? () from /usr/lib/dri/radeonsi_dri.so
#4  0x00007fa1d21a6259 in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007fa1d1f8b5e3 in clone () from /usr/lib/libc.so.6
```
But  2 Threads look different:

```
Thread 1 (Thread 0x7fa1d1d8e780 (LWP 6360)):
#0  0x00007fa1c5f6c860 in vkGetPhysicalDeviceProperties2 () from /usr/lib/libvulkan.so.1
#1  0x000055ace41a2066 in vr::CHmdWindowSDL::CreateVulkanInstance() ()
#2  0x000055ace41a3579 in vr::CHmdWindowSDL::CHmdWindowSDL(vr::CHmdDistort*, int, int, unsigned int, unsigned int, float) ()
#3  0x000055ace417596c in vr::CHmdDistort::Initialize(TVRSharedState<VRCompositorState_t, false>*, vr::IVRIPCResourceManagerClient*, bool) ()
#4  0x000055ace41f12cc in CVRCompositor::Init() ()
#5  0x000055ace41f1abd in RealMain(unsigned int, ParsedArguments_t&) ()
#6  0x000055ace4170270 in main ()


Thread 4 (Thread 0x7fa1ceb27640 (LWP 6366)):
#0  0x00007fa1d21b28ca in __futex_abstimed_wait_common64 () from /usr/lib/libpthread.so.0
#1  0x00007fa1d21aeae8 in __new_sem_wait_slow64.constprop.0 () from /usr/lib/libpthread.so.0
#2  0x00007fa1d295df28 in ?? () from /home/black/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/libSDL2-2.0.so.0
#3  0x00007fa1d295e055 in ?? () from /home/black/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/libSDL2-2.0.so.0
#4  0x00007fa1d28e2c18 in ?? () from /home/black/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/libSDL2-2.0.so.0
#5  0x00007fa1d28e267b in ?? () from /home/black/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/libSDL2-2.0.so.0
#6  0x00007fa1d295dc59 in ?? () from /home/black/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/libSDL2-2.0.so.0
#7  0x00007fa1d21a6259 in start_thread () from /usr/lib/libpthread.so.0
#8  0x00007fa1d1f8b5e3 in clone () from /usr/lib/libc.so.6
```

Any idea?

**Comment by spiderbit** [comment]
hmm because as far as I understand you can also have steamvr working over monando I managed to install monando in archlinux, with this modified openhmd driver and I guess I get similar errors when I try to start monado-service maybe that helps:
```

 # monado-service 
 INFO [disable_drivers_from_conflicts] Disabling vive because we have survive
 INFO [wmr_read_config] Manufacturer: HP Inc.
 INFO [wmr_read_config] Device: HP VR1000-2xxx
 INFO [wmr_read_config] Serial: 8CC001Z002
 INFO [wmr_read_config] UID: {337864A4-568E-5D82-A15E-7AC9043B8744}
 INFO [wmr_read_config] Name: HP Reverb VR Headset VR1000-2xxx
 INFO [wmr_read_config] Revision: RevB
 INFO [wmr_read_config] Revision Date: 2020-01-03
 INFO [wmr_hmd_create] Found WMR headset type: HP Reverb
 INFO [wmr_hmd_create] FoV eye 0 angles left -0.875178 right 0.708848 down -0.787777 up 0.787879
 INFO [wmr_hmd_create] Render texture range -1.197855, -1.004770 to 0.857528, 1.004975
 INFO [wmr_hmd_create] FoV eye 1 angles left -0.707972 right 0.877946 down -0.788770 up 0.788600
 INFO [wmr_hmd_create] Render texture range -0.856009, -1.006766 to 1.204616, 1.006423
 INFO [wmr_hmd_activate_reverb] Sent activation report, sleeping for compositor.
 INFO [wmr_source_stream_start] Starting WMR stream in tracking mode
 INFO [compute_frame_size] WMR camera framebuffer 1280 x 480 - 616538 transfer size
 INFO [wmr_camera_start] WMR camera started
Info: Loaded drivers: HTCVive
DEBUG [xrt_gfx_provider_create_system] Doing init 0x564dce783d80
DEBUG [vk_select_physical_device] vkEnumeratePhysicalDevices: VK_ERROR_INITIALIZATION_FAILED
ERROR [compositor_check_vulkan_caps] vk_create_device: VK_ERROR_INITIALIZATION_FAILED
	Failed to create VkDevice.
```

**Comment by spiderbit** [comment]
when I setup amdgpu driver like described here:
https://wiki.archlinux.org/title/AMDGPU#Enable_Southern_Islands_(SI)_and_Sea_Islands_(CIK)_support

vulkaninfo and the monando-service command works, when I then try steamvr I kind of get the HMD show a picture, it's just strange like zoomed in to big and to far away like there I am a cameleon and my eyes are on the side of my head not in front, there is parts between the eyes missing.

When I switch back to radeon vulkaninfo brings errors is that normal? I mean I used another openhmd compatible hmd before and I did not need to switch to amdgpu driver, so I don't think it's necessary.

```
$ vulkaninfo 
ERROR: [Loader Message] Code 0 : loader_scanned_icd_add: Driver /usr/lib/libvulkan_radeon.so supports Vulkan 1.2, but only supports loader interface version 4. Interface version 5 or newer required to support this version of Vulkan (Policy #LDP_DRIVER_7)
ERROR: [Loader Message] Code 0 : setup_loader_term_phys_devs:  Failed to detect any valid GPUs in the current config
ERROR: [Loader Message] Code 0 : setup_loader_tramp_phys_devs:  Failed during dispatch call of 'vkEnumeratePhysicalDevices' to lower layers or loader to get count.
ERROR at /build/vulkan-tools/src/Vulkan-Tools-1.2.203/vulkaninfo/vulkaninfo.h:230:vkEnumeratePhysicalDevices failed with ERROR_INITIALIZATION_FAILED
```

**Comment by thaytan** [comment]
> hmm because as far as I understand you can also have steamvr working over monando I managed to install monando in archlinux, with this modified openhmd driver and I guess I get similar errors when I try to start monado-service maybe that helps:
> 
> ```
> 
>  # monado-service 
>  INFO [disable_drivers_from_conflicts] Disabling vive because we have survive
>  INFO [wmr_read_config] Manufacturer: HP Inc.
>  INFO [wmr_read_config] Device: HP VR1000-2xxx
>  INFO [wmr_read_config] Serial: 8CC001Z002
>  INFO [wmr_read_config] UID: {337864A4-568E-5D82-A15E-7AC9043B8744}
>  INFO [wmr_read_config] Name: HP Reverb VR Headset VR1000-2xxx
>  INFO [wmr_read_config] Revision: RevB
>  INFO [wmr_read_config] Revision Date: 2020-01-03
>  INFO [wmr_hmd_create] Found WMR headset type: HP Reverb
>  INFO [wmr_hmd_create] FoV eye 0 angles left -0.875178 right 0.708848 down -0.787777 up 0.787879
>  INFO [wmr_hmd_create] Render texture range -1.197855, -1.004770 to 0.857528, 1.004975
>  INFO [wmr_hmd_create] FoV eye 1 angles left -0.707972 right 0.877946 down -0.788770 up 0.788600
>  INFO [wmr_hmd_create] Render texture range -0.856009, -1.006766 to 1.204616, 1.006423
>  INFO [wmr_hmd_activate_reverb] Sent activation report, sleeping for compositor.
>  INFO [wmr_source_stream_start] Starting WMR stream in tracking mode
>  INFO [compute_frame_size] WMR camera framebuffer 1280 x 480 - 616538 transfer size
>  INFO [wmr_camera_start] WMR camera started
> Info: Loaded drivers: HTCVive
> DEBUG [xrt_gfx_provider_create_system] Doing init 0x564dce783d80
> DEBUG [vk_select_physical_device] vkEnumeratePhysicalDevices: VK_ERROR_INITIALIZATION_FAILED
> ERROR [compositor_check_vulkan_caps] vk_create_device: VK_ERROR_INITIALIZATION_FAILED
> 	Failed to create VkDevice.
> ```

Just FYI - OpenHMD isn't in use in this trace. This is using the Monado native WMR driver, which is further along than the OpenHMD one in any case. I don't know why you're seeing incorrect display in the headset. The values for render ranges look plausible from the log.

**Comment by spiderbit** [comment]
@thaytan Really hmm, could it have to do with gnomes display zoom or how that is called, that I have the desktop at 200% and while activating steamvr it activates / deactivates this zoom sometimes but for the monitor.

Maybe should test it outside of gnome and bite the sour apple to test the device in windows to eleminate the chance that the device is somehow hardware damaged, but that would be a strange defekt.

Another question would be I have bought a displayport -> mini-diplayport adapter because that gpu don't has full size displayport slots, that should not matter, right? I mean on the openhmd front nothing has chanced since I switched even the gpu.

Can't remember having such a persistent unfixable problem that should be fixable, very strange.
All this vulkan stuff should not matter because I used openhmd / steamvr with a Samsung Odyssey without any changes or was amdgpu vulkan introduced as new requirement for openhmd recently.

**Comment by thaytan** [comment]
For Monado questions, I suggest joining the Monado discord

**Comment by Wallbraker** [comment]
Do you have a AMD CPU, 3xxx or 4xxx series?

**Comment by spiderbit** [comment]
@Wallbraker I think it's 2xxx 2700x

**Comment by Wallbraker** [comment]
Yeah there are some problems with the Reverb G2 and various AMD chipsets, like the B550 and X570.

**Comment by spiderbit** [comment]
I think I have a B450, that said I think I have tested it at some point with my old Intel Pentium G4560 system.

But that said depending on the route I take openhmd vs Monando I get different "bugs", so how exactly would this "problems" materialize? Is it on the Monando or Openhdm front or on both?

**Comment by spiderbit** [comment]
@thaytan I don't think steamvr actually uses that or does that monando-service trace look like it startet? I assume it did not start when it ends with a error?

I don't know all this is so untransparent and convoluted and bad documentated.

**Comment by spiderbit** [comment]
ok just tested the kit in a fresh Windows 11 install, works without problem, so there is no hardware issue.

**Comment by spiderbit** [comment]
@thaytan now that I tested if the hardware is ok, and I even tried fedora and archlinux with that hmd, I tested different kernels, I wonder if I fucked something somewhere up and would want to try a new installation.

What would be in your oppinion the optimal distro to test the openhmd driver with steamvr? Debian / Ubuntu / a fresh arch / PopOs.

I guess debian/ubuntu would be best because there are monado packages? So I can test this route first?

**Comment by thaytan** [comment]
The best option for G2 right now is to use Monado without OpenHMD.

**Comment by spiderbit** [comment]
@thaytan But I have a G1... but the answer should be the same right?

**Comment by spiderbit** [comment]
I assume it must have to do something with professional edition vs other edition probably the code works for the other version that I don't have, debian didn't help much.

I get some semi steamvr stuff running yet mostly the resolution or calibration or something seems to be fucked, and if I try vr-video-player that uses steam nothing works.

The time I wasted into that hmd is not worth it as broke as I am, try to get it sold (it works under windows so it's not defect) and hopefully get a G2 for 50-150 EUR price difference.

Of course it would suck if that also would also not work, but seems to be the best move left.

**Comment by thaytan** [comment]
You could jump on the #driver-wmr channel in the monado discord, if you're up for doing some more debugging interactively.

**Comment by spiderbit** [comment]
@thaytan I have now a hp reverb g2 and more or less the same problems.

It seems like that the parts are all there but the pieces don't fit together. I get the initialization, I can use the hmd as desktop the tracknig works but it opens the hmd window on the monitor not the hmd.

I don't really understand the vulkan stuff, I didn't had to enable anything vulkan boot stuff with my old Samsung Odysee did something in the amd drivers change or is that a new dependency?

**Comment by thaytan** [comment]
Probably best to take this to the Monado discord and gitlab

**Comment by spiderbit** [comment]
@thaytan well I will get rid of one of the 2 HMDs now because and more likely it will be the G2 because the software behaves identically so it does not seem to be a issue with some G1 specific things.

And yes I often looked into that discord, sadly it's hard to catch a person helping me when I try to connect. Maybe some designated week day or hours where you don't guarantee help but declare those to be more likely to get help would help.

Even the 2 times I got help, it was very ineffective and didn't feel like there is a high chance that I get a patch or something that fixes it.

Very frustrating process, I can replace the Distribution, the mainboard / processor, the gpu, the HMD itself nothing helps, therefor I can't see that I am a isolated corner case, many if not most people having a Reverb will have the same experience if they want to use SteamVR.

So I would suggest removing or modifying the status on this cards on the monado site at least. If I replace every single hardware and software part and still don't get it to work than it can't be a isolated corner case.

Sorry for my tone but I am no full time Openhmd / Monado tester and even if I find time to try to debug that I find nobody in the discord.

I know that is unfair because you do this not paid probably, but that does change my frustrating experiences.

I am not here to burn some time because I am bored, I either need a realistic path that has high chance of succesful implementing of patches or something, I doubt anybody else even tried SteamVR with the devices or they all use a specific version of Ubuntu or something. I thought first maybe because of the 2 versions of the G1 or because the dev seem to have often the G2 that I have a special setup that behaves differently, but I can't see that steamvr works with anybody at this point with a reverb, or you all have Nvidia cards that would be the one thing I did not try yet.

Sorry for my rant, but I am very frustrated and my hopes are pretty down. It's not like VR support in general seems to go anywhere in linux how many years do we wait for controller support? that's probably the reason nobody even cares to use this software therefor you don't know that it's fundamentally not working (at least with steamvr and that hmd(s)).

**Comment by spiderbit** [comment]
@thaytan so I am back with the G1 and after having now a many years older GPU rx 5600 xt instead of the hd7950 or rx480 which I had at some point, steamvr kind of works now.

So in short if you have the same problem one solution/workaround is to buy a newer grafic card at least on the AMD side of things.

That said when I use the vr-video-player:
https://aur.archlinux.org/packages/vr-video-player-git

That worked with the same setup (openhmd-steamvr) and the Samsung Odysee hmd, it starts but the eyes are seperated so you see with one eye the left part of the application and the other eye the right side like there is a huge gap between the eyes.
